# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_fullname', models.CharField(max_length=100)),
                ('user_mail_id', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
            ],
        ),
    ]
