# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-23 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('user_rating', models.CharField(max_length=100)),
                ('image_name', models.CharField(max_length=100)),
            ],
        ),
    ]
