# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-23 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Detail',
        ),
        migrations.DeleteModel(
            name='UserRegistration',
        ),
    ]
