# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-27 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_myprofileform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofileform',
            name='user_fullname',
            field=models.CharField(default=1, max_length=100, verbose_name='kjkjkjkj'),
        ),
    ]
